### ISSUE TITLE
Something went wrong! file an issue at https://tiny.one/readme-stats

### ISSUE THREAD

**Issue by qhy040404** [anuraghazra/github-readme-stats#1759]
**Describe the bug**
Maximum retries exceeded

**Expected behavior**
Correct statistic data

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/45379733/168976524-ab4c426a-8670-4b97-90e1-4f91e9f6c610.png)

**Additional context**
Please add an env variable called PAT_1 with your github token in vercel

**Comment by qhy040404** [comment]
It seems like all cards are failed to generate

**Comment by dongjji** [comment]
I got the same issue too.

**Comment by metleeha** [comment]
I got the same issue too.

**Comment by pro465** [comment]
same

**Comment by josix** [comment]
It seems like this error is fixed now but I'm not sure what has been done on the server-side.

**Comment by qhy040404** [comment]
> It seems like this error is fixed now but I'm not sure what has been done on the server-side.

That's why i didn't close this issue

**Comment by dongjji** [comment]
I lost one commit log during this time.
Is this a github server's error?

**Comment by qhy040404** [comment]
The card on your readme.md is precached, you can open the url and check it

> I lost one commit log during this time. Is this a github server's error?

**Comment by qiaohuang** [comment]
> I lost one commit log during this time. Is this a github server's error?

The same. It's all fixed now.

**Comment by dongjji** [comment]
> 
I think mine is not fixed
Did you get same issue? 
@qiaohuang

**Comment by qiaohuang** [comment]
Yes, there may be server delays, my latest commit count just refreshed.
@dongjji

**Comment by dongjji** [comment]
![image](https://user-images.githubusercontent.com/81581204/168985859-afebbd4b-005e-4b56-9ff5-d4d0fabb28de.png)
I lost 21 commits on it. Sorry for annoying you.
Did your commits come back after the delay finished?
@qiaohuang

**Comment by DSDimitrov19** [comment]
I got the same issue as well.

**Comment by rickstaa** [comment]
@qhy040404 Thanks for creating this issue! The problem is related to https://github.com/anuraghazra/github-readme-stats/issues/1471. As explained in https://github.com/anuraghazra/github-readme-stats/issues/1471#issuecomment-979306704, the best solution is to deploy your vercel instance. A guide on how to do this can be found [here](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance).

About the commits being lost, I think the GitHub-readme-stats plugin can not cause this since we directly use GitHub's GraphQL API. Again, deploying your Vercel instance gives the best results since Github-readme-stats then has access to your private repositories. When using the public Vercel instance, please make sure that you show private contributions on your profile. Also, keep in mind that we use caching to keep the server load down (see https://github.com/anuraghazra/github-readme-stats#gradient-in-bg_color).

![image](https://user-images.githubusercontent.com/17570430/168988161-770c8946-6d88-42ac-8d59-e73e82bc384e.png)

**Comment by rickstaa** [comment]
I will close this for now since this issue is already being discussed in #1471.

**Comment by qiaohuang** [comment]
> ![image](https://user-images.githubusercontent.com/81581204/168985859-afebbd4b-005e-4b56-9ff5-d4d0fabb28de.png) I lost 21 commits on it. Sorry for annoying you. Did your commits come back after the delay finished? @qiaohuang

You mean this project, [GitHub Readme Streak Stats](https://github-readme-streak-stats.herokuapp.com/)? Seems unrelated to this issue.
Sorry, I haven't used it. Maybe you can open another issue in the project repo.

**Comment by rickstaa** [comment]
@qiaohuang Ha, I did not look at the picture. That is indeed another project! Thanks a lot for jumping in on this one. 🚀

**Comment by dongjji** [comment]
Sorry I used the picture using (github streak stats) for figuring out the total lost of commits.
Anyway Thanks for listening me. I will check it out with different way.
@qiaohuang

**Comment by josix** [comment]
Thank you @rickstaa for the quick reply.

**Comment by komporbakar** [comment]
same guys
