### ISSUE TITLE
Update themes documentation & CI

### ISSUE THREAD

**Issue by rickstaa** [anuraghazra/github-readme-stats#3404]
### Is your feature request related to a problem? Please describe.

To decrease maintenance, we temporarily pause new theme additions (see https://github.com/anuraghazra/github-readme-stats/pull/3138#issuecomment-1774134509). This change, however, still needs to be communicated to our users, and the CI should be updated.

### Describe the solution you'd like

To ensure that this change is as transparent as possible, we should:

- [ ] Update the [CONTRIBUTING.md](CONTRIBUTING.md) to communicate the change.
- [ ] Update the [README.md](README.md) to communicate the change.
- [ ] Disable the [preview-theme.yml](https://github.com/anuraghazra/github-readme-stats/blob/master/.github/workflows/preview-theme.yml).
- [ ] Add a new action that closes new theme pull requests and adds an explanation message.

**Comment by qwerty541** [comment]
@rickstaa I think that it's good decision to temporary halt themes addition, since it's prevent wasting our time on a lot of spam pull requests. I only want you to review two my pull requests before (https://github.com/anuraghazra/github-readme-stats/pull/3401 and https://github.com/anuraghazra/github-readme-stats/pull/3400), recently i did a little work to allow users contribute gradient themes and i don't want the result of my work to be lost, since it would be userful if we're going to enable back themes addition in future.

**Comment by rickstaa** [comment]
> @rickstaa I think that it's good decision to temporary halt themes addition, since it's prevent wasting our time on a lot of spam pull requests. I only want you to review two my pull requests before (#3401 and #3400), recently i did a little work to allow users contribute gradient themes and i don't want the result of my work to be lost, since it would be userful if we're going to enable back themes addition in future.

Of course! Great additions if we enable the theme contributions in the future. I merged your PRs into the main branch!

**Comment by qwerty541** [comment]
> > @rickstaa I think that it's good decision to temporary halt themes addition, since it's prevent wasting our time on a lot of spam pull requests. I only want you to review two my pull requests before (#3401 and #3400), recently i did a little work to allow users contribute gradient themes and i don't want the result of my work to be lost, since it would be userful if we're going to enable back themes addition in future.
> 
> Of course! Great additions if we enable the theme contributions in the future. I merged your PRs into the main branch!

Thanks! Looks like i made a mistake while implementing feature to allow addition of gradient themes and `preview-theme` workflow still fails. I have opened pull request https://github.com/anuraghazra/github-readme-stats/pull/3427 to resolve this issue, please check it.

**Comment by rickstaa** [comment]
@qwerty541 closing this as we implemented all todos.
