### ISSUE TITLE
Public deployment paused

### ISSUE THREAD

**Issue by shivpat09** [anuraghazra/github-readme-stats#3851]
### Describe the bug

So the commands that have been set to show the most used languages or commits and stuff seem to not be working. They come up as the name of the image in blue text with the weird image icon next to it.

### Expected behavior

I expected the charts and data to pop up like normal, or as it is shown in the README.

### Screenshots / Live demo link

![image](https://github.com/user-attachments/assets/fb9ab0bd-0a02-4a73-a0e8-72e503a870e3)

**Comment by justinvforvendetta** [comment]
same here.

**Comment by PLeonLopes** [comment]
Same here, probably cooking an update 👀

**Comment by CoolCat467** [comment]
If you hit https://github-readme-stats.vercel.app/, we get a `DEPLOYMENT_PAUSED` response code.

**Comment by shivenpatel399** [comment]
Ok, that makes sense. Sorry if I caused any trouble, I tried this stats thing for the first time yesterday, so I don't know much about it.

**Comment by afan0918** [comment]
same here

**Comment by kpryu6** [comment]
same here..

**Comment by qwerty541** [comment]
Hey guys! Thanks for your reports. Looks like something was happened with Vercel account of Anurag since each request returns the page on screenshot. Unfortunately only Anurag has access to the account, I sent him a message, now waiting for his response. If you want to make your cards work right now, then you can [deploy your own Vercel instance](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#on-vercel).

![Снимок экрана от 2024-07-18 05-17-20](https://github.com/user-attachments/assets/27bcfab2-e771-4312-be4e-e2d37e398f31)

**Comment by skson0x6ab** [comment]
same here

**Comment by hootyhoot** [comment]
> Hey guys! Thanks for your reports. Looks like something was happened with Vercel account of Anurag since each request returns the page on screenshot. Unfortunately only Anurag has access to the account, I sent him a message, now waiting for his response. If you want to make your cards work right now, then you can [deploy your own Vercel instance](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#on-vercel).
> 
> ![Снимок экрана от 2024-07-18 05-17-20](https://private-user-images.githubusercontent.com/53787217/349760602-27bcfab2-e771-4312-be4e-e2d37e398f31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzc5NjgsIm5iZiI6MTcyMTI3NzY2OCwicGF0aCI6Ii81Mzc4NzIxNy8zNDk3NjA2MDItMjdiY2ZhYjItZTc3MS00MzEyLWJlNGUtZTJkMzdlMzk4ZjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA0NDEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1Zjc2ODViMjAyYzM1MDdhYWMyNTc2YmI4NjAyYzk2NTc0MGQyMjU5OGM1NzVhNTg0OTA4MzM4MGYwODcyZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OU5Qm7K76_DAKaRhKPSxgrvaL-J2A6_LXKppvDGbbCw)

Problem persists on self hosted Vercel deployment, seems like its an issue with the GitHub API in the back fetching it.

**Comment by Honzoraptor31415** [comment]
Also having this problem

**Comment by AZCodingAccount** [comment]
guys, if it works out, let me know

**Comment by qwerty541** [comment]
Hey guys! All this time the public instance was deployde on Vercel on the account with enterprise plan provided for free for Anurag. I just received a message from Anurag that Vercel stopped their OSS sponsorship and account was returned to basic plan, so when the limits was exceeded the deployment was paused. As I understand, at the moment Anurag returned it to work with own money, but in the near future we have to migrate on another cloud provider because Vercel is very expensive. Therefore, deployment on the [github-readme-stats.vercel.app](https://github-readme-stats.vercel.app/) will be shutdown soon. For now I recommend you all to [deploy your own Vercel instances](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#on-vercel) in order to avoid impact of future shutdown of public instance.

**Comment by Rudxain** [comment]
I wish #2537 merges soon

**Comment by SUGAN-developer** [comment]
> ### Describe the bug
> So the commands that have been set to show the most used languages or commits and stuff seem to not be working. They come up as the name of the image in blue text with the weird image icon next to it.
> 
> ### Expected behavior
> I expected the charts and data to pop up like normal, or as it is shown in the README.
> 
> ### Screenshots / Live demo link
> ![image](https://private-user-images.githubusercontent.com/132844761/349694682-fb9ab0bd-0a02-4a73-a0e8-72e503a870e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NjE3MzAsIm5iZiI6MTcyMTQ2MTQzMCwicGF0aCI6Ii8xMzI4NDQ3NjEvMzQ5Njk0NjgyLWZiOWFiMGJkLTBhMDItNGE3My1hMGU4LTcyZTUwM2E4NzBlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQwNzQzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2FmMTU5ZDA1OTkwOTkxYjQ2MGRkYTQ4MGIyYjE2OWQ1OTY1ZDE1NjMyNTEyZmNlNTMxOWVmYmEyMjc2NzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LQATxDrRxPqxgU_jHPdTxQq2j4b7wjUTQUKP9skSC9A)
> 
> ### Additional context
> _No response_


<a href="https://github.com/anuraghazra/github-readme-stats">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats" />
</a>
<a href="https://github.com/anuraghazra/convoychat">
  <img align="center" src="  " />
</a>

put link inside the src and change the username

**Comment by CrownAlexanRaven** [comment]
hey its back online, but it was offline because @anuraghazra was, actually ill quote it directly
> All this time the public instance was deployed on Vercel on the account with enterprise plan provided for free for Anurag. I just received a message from Anurag that Vercel stopped their OSS sponsorship and account was returned to basic plan, so when the limits was exceeded the deployment was paused. As I understand, at the moment Anurag returned it to work with own money, but in the near future we have to migrate on another cloud provider because Vercel is very expensive.
Basically Vercel pulled their sponsorship which this is using and he had to bring it back online with his own cash.

I would say deploy it yourself because then u will be immune to outages on the current hosted one on vercel.
Also... 
> Therefore, deployment on the [github-readme-stats.vercel.app](https://github-readme-stats.vercel.app/) will be shutdown soon. For now I recommend you all to [deploy your own Vercel instances](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#on-vercel) in order to avoid impact of future shutdown of public instance.

So yes issues fixed, and if you wanna see what im quoting [here ya go](https://github.com/anuraghazra/github-readme-stats/issues/3854#issuecomment-2237326765)

**Comment by ParsaKSH** [comment]
> ### Describe the bug
> So the commands that have been set to show the most used languages or commits and stuff seem to not be working. They come up as the name of the image in blue text with the weird image icon next to it.
> 
> ### Expected behavior
> I expected the charts and data to pop up like normal, or as it is shown in the README.
> 
> ### Screenshots / Live demo link
> ![image](https://github.com/user-attachments/assets/fb9ab0bd-0a02-4a73-a0e8-72e503a870e3)
> 
> ### Additional context
> _No response_

We are experiencing it again

**Comment by xxshubhamxx** [comment]
Same issue happening again

**Comment by TIMER-err** [comment]
same issue

**Comment by xxshubhamxx** [comment]
It should be resolved tomorrow :)

**Comment by akshatjain-official** [comment]
> It should be resolved tomorrow :)
I am still facing an issue with the link- it's still saying service unavailable

<img width="751" height="461" alt="Image" src="https://github.com/user-attachments/assets/8369367f-c28f-4c47-baec-0562a9d36efc" />

Please update me, once you find it resolved.

Thanks and Regards,
Akshat Jain

**Comment by BOTOOM** [comment]
Before commenting on the error if you are reporting it, please read the following [comment](https://github.com/anuraghazra/github-readme-stats/issues/3851#issuecomment-2237316047)

**Comment by Cactusinhand** [comment]
Hi everyone, you can try this tool [GithubCard](https://githubcard.com/)

For more details, see #4682

**Comment by mg0x7BE** [comment]
https://github.com/anuraghazra/github-readme-stats/issues/4658#issuecomment-3663877856 fixed the problem

**Comment by rickstaa** [comment]
As we are no longer sponsored by Vercel (see [this April 2024 message](https://github.com/anuraghazra/github-readme-stats/issues/3851#issuecomment-2237316047)), we can no longer reliably operate the public instance at its current scale. The public endpoint remains available, but users should expect downtime.

To provide a stable alternative, we have released a new [GitHub Action](https://github.com/marketplace/actions/github-readme-stats-action), which is now the recommended way to use the project. This approach is significantly more stable and allows for [more accurate tracking](https://github.com/readme-tools/github-readme-stats-action) as improvements are introduced.

Alternatively, you can deploy the project on your [own instance](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#deploy-on-your-own), which has been the recommended setup for years and supports private data.

**Comment by rickstaa** [comment]
> As we are no longer sponsored by Vercel (see [this April 2024 message](https://github.com/anuraghazra/github-readme-stats/issues/3851#issuecomment-2237316047)), we can no longer reliably operate the public instance at its current scale. The public endpoint remains available, but users should expect downtime.
> 
> To provide a stable alternative, we have released a new [GitHub Action](https://github.com/marketplace/actions/github-readme-stats-action), which is now the recommended way to use the project. This approach is significantly more stable and allows for [more accurate tracking](https://github.com/readme-tools/github-readme-stats-action) as improvements are introduced.
> 
> Alternatively, you can deploy the project on your [own instance](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#deploy-on-your-own), which has been the recommended setup for years and supports private data.

I just noticed the deployment is still paused and the endpoint not available anymore. I would recommend people to use the github action or any of the self deployment options available for now.

**Comment by rickstaa** [comment]
I’ve been in touch with @martin-mfg, who has stepped up to help return this project to active maintenance. We’ve agreed to combine efforts to ensure the project is properly maintained going forward.

For now, development will take place under @martin-mfg’s organization at https://github.com/stats-organization. We have also contacted @anuraghazra to discuss contributing directly to https://github.com/anuraghazra/github-readme-stats or https://github.com/github-readme-stats], which he originally created, and to explore obtaining the necessary permissions.

In the meantime, we will work from the https://github.com/stats-organization repository and backport changes to the upstream project whenever possible.

**Comment by hesreallyhim** [comment]
thanks @rickstaa and @martin-mfg that's great to hear! i have a few questions that I hope will be helpful in keeping things organized moving forward:

- can you provide some recommendations for users who wish to (continue to) self-host their own deployments? for example, with respect to attribution - should this new organization be included? which repo/branch do you recommend as being the "upstream" going forward? in my case, I serve pin cards for many many repos (from a self-hosted deployment), so the Action alone does not meet my use case.
- what sort of issues/PRs do you currently wish to accept? is the project in KTLO mode or should people still propose enhancements?
- it may be good to enable Discussions in the event that you do not with to accept enhancements at the moment.

Thanks!

If you would like help with triage I am also happy to contribute on that front.

**Comment by martin-mfg** [comment]
Thanks @hesreallyhim for bringing up these questions!

> which repo/branch do you recommend as being the "upstream" going forward?

For self-hosting, as of now my general recommendation is to use/fork the ~~`master`~~ `next` branch of https://github.com/stats-organization/github-readme-stats. It should mostly be identical to anuraghazra/github-readme-stats, but might be maintained more regularly, as more of the active maintainers have write access to it.

> with respect to attribution - should this new organization be included?

Most importantly, attribution should go to whichever project you are forking/using. If possible, I'd recommend to briefly mention both, [anuraghazra/github-readme-stats](https://github.com/anuraghazra/github-readme-stats) and [stats-organization](https://github.com/stats-organization).

> it may be good to enable Discussions

Discussions are now enabled in [stats-organization/github-readme-stats](https://github.com/stats-organization/github-readme-stats), [stats-organization/github-stats-extended](https://github.com/stats-organization/github-stats-extended) and [stats-organization/github-readme-stats-action](https://github.com/stats-organization/github-readme-stats-action).

> what sort of issues/PRs do you currently wish to accept? is the project in KTLO mode or should people still propose enhancements?

* Bugfixes which can be reviewed quickly would be great.
* What I currently don't want to spend time on are PRs with new functionality. Instead of reviewing individual PRs with new functionality for the project, I would currently rather like to work on fully releasing [stats-organization/github-stats-extended](https://github.com/stats-organization/github-stats-extended). Because this includes [multiple of the most requested enhancements](https://github.com/stats-organization/github-stats-extended/blob/master/docs/fork.md#key-differences).
* At the moment I view [stats-organization/github-stats-extended](https://github.com/stats-organization/github-stats-extended) as "release candiate". It would be great if some more people could test it, especially the new features. This way we can ensure everything works and the server can handle the load.

> in my case, I serve pin cards for many many repos (from a self-hosted deployment), so the Action alone does not meet my use case.

Why can't you generate all the pin cards you need via an action? Are you hitting the rate limiting of GitHub's API?

**Comment by soulteary** [comment]
a simple solution https://github.com/anuraghazra/github-readme-stats/issues/4747

**Comment by heliocarlitos** [comment]
# Web Version Alternative – No-Code GitHub README Builder 🚀 #4769

I created a web version based on this library that allows you to create and customize GitHub statistics for a clean, organized, and professional README, without needing to write any code.

This tool is especially useful for those starting on GitHub or who have difficulty understanding documentation but want to improve their profile presentation.

### Access the Application

[https://nice-readme.vercel.app/](https://nice-readme.vercel.app/)

<a href="https://nice-readme.vercel.app/streak-stats" target="_blanck">
<img src="https://heliocarlitos.vercel.app/_next/static/media/demo_nice_readme_1.033e0eaa.webp" />
</a>

**Comment by maquejp** [comment]
Still not solved??

**Comment by heliocarlitos** [comment]
Hi @maquejp 
Did you access the tool’s website and try to use it. If you did not, please try it. Otherwise, explain in detail how you proceeded and why it did not work. 

[https://nice-readme.vercel.app/](https://nice-readme.vercel.app/)

**Comment by maquejp** [comment]
> Hi [@maquejp](https://github.com/maquejp) Did you access the tool’s website and try to use it. If you did not, please try it. Otherwise, explain in detail how you proceeded and why it did not work.
> 
> https://nice-readme.vercel.app/

In fact, I am looking to have stats accross my "organisation" not only per repo.... The "still not solved" was about the "original" tool. Yours works, no issue

**Comment by heliocarlitos** [comment]
It is recommended to consult the official documentation to confirm whether the tool supports organizations. Personally, I believe that such support does not exist. If it does exist, the observed behaviour suggests that it is not working correctly.

This issue is mentioned in the following official comment:
[GitHub issue comment](https://github.com/anuraghazra/github-readme-stats/issues/3851#issuecomment-2237316047)

**Comment by hesreallyhim** [comment]
@maquejp how big is your organization? my repo has over 150 pin cards and it works fine - do you mean stats where OWNER is an organization? I have a proper fork where that is fixed for pin cards and could try to accommodate username/owner = organization if you can tell me your use case. e.g. this is langchain-ai/langchain, works fine:

https://github-readme-stats-plus-theta.vercel.app/api/pin/?username=langchain-ai&repo=langchain

@heliocarlitos your project looks nice but this repo - https://github.com/heliocarlitos/nice-readme - has no LICENSE and therefore by default is copyright controlled; and also it has no attribution to the authors of the work you are using such as anuraghazra, which is a violation of MIT. Please support open source authors by respecting attribution requirements.

**Comment by heliocarlitos** [comment]
@hesreallyhim 
Thank you for the information and for pointing this out. I am already working on it and will soon comply with all obligations and best practices of the open source community.

**Comment by hesreallyhim** [comment]
Thanks @heliocarlitos i think the truth is a lot of people just don't know what's required license-wise. And it can be complicated. But yeah main thing is if a repo has no LICENSE then by default it's copyright. And MIT is permissive but requires explicit attribution.

**Comment by heliocarlitos** [comment]
Thank you for the clarification @hesreallyhim. I agree that licensing can be confusing, especially at the beginning. I appreciate you taking the time to explain it, and I will make sure the license and attribution are handled correctly.

**Comment by maquejp** [comment]
> [@maquejp](https://github.com/maquejp) how big is your organization? my repo has over 150 pin cards and it works fine - do you mean stats where OWNER is an organization? I have a proper fork where that is fixed for pin cards and could try to accommodate username/owner = organization if you can tell me your use case. e.g. this is langchain-ai/langchain, works fine:
> 
> https://github-readme-stats-plus-theta.vercel.app/api/pin/?username=langchain-ai&repo=langchain
@hesreallyhim  Only me ;)  I am discovering and trying things. In fact, waht I would like to have is on my Organisation overview the global stats, the stats per repo, and the stats per projects. This is the last part, the stats (issues open, closed, pending...) ,I have difficulties to have. For the time being I use uses: lowlighter/metrics@latest

**Comment by hesreallyhim** [comment]
@maquejp 
ok that's pretty cool so what's wrong with the lowlighter project for your needs?

**Comment by maquejp** [comment]
> [@maquejp](https://github.com/maquejp) ok that's pretty cool so what's wrong with the lowlighter project for your needs?

@hesreallyhim noting really wrong, just that it is not 100% what I want. Expecially the breakdown per project/repo

**Comment by VanillaNahida** [comment]
same here... :(
if it works out, let me know, thanks :)

<img width="1112" height="795" alt="Image" src="https://github.com/user-attachments/assets/56d3373b-70e7-4d10-acbe-9785742b076e" />

**Comment by Cactusinhand** [comment]
> same here... :( if it works out, let me know, thanks :)
> 
> <img alt="Image" width="1112" height="795" src="https://private-user-images.githubusercontent.com/151599587/571034701-56d3373b-70e7-4d10-acbe-9785742b076e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzQ4MzE3NTgsIm5iZiI6MTc3NDgzMTQ1OCwicGF0aCI6Ii8xNTE1OTk1ODcvNTcxMDM0NzAxLTU2ZDMzNzNiLTcwZTctNGQxMC1hY2JlLTk3ODU3NDJiMDc2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMzMFQwMDQ0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDRmOThmZThjMzQxZjBkMzM4MDZiMjc3Mjk0YzhhY2E2NzY4ZDA5NmYxMTg4ZWJlYTE0YjFhNGExNDViNDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.j2yJePmCQat5dpyqX56cHRIv7haPfOFgUg-EjisBqfc">

https://github.com/anuraghazra/github-readme-stats/issues/3851#issuecomment-3619757592
